# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy packages
COPY package*.json ./

#Install dependencies
RUN npm install

# Install Axios and Bootstrap
RUN npm install axios@1.2.1
RUN npm install bootstrap@v5.2.3

# Copy app files
COPY . .

# Build the app
RUN npm run build

# Set environment variables
ENV REACT_APP_API_URL=https://api.example.com

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
